# Usa una imagen base de Python
FROM python:3.10-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de requisitos y luego instala las dependencias
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación en el contenedor
COPY . .

# Expone el puerto en el que tu aplicación estará escuchando (ajústalo si es diferente)
EXPOSE 8080

# Comando para correr la aplicación (ajústalo dependiendo del framework que uses)
# Para Flask:
# python server.py
CMD ["python", "main.py"]