[tool.black]
line-length = 100
exclude = '''
/(
    | env
    | venv
    | .venv
    | .venv
    | .git
    | .vscode
)/

'''


[tool.isort]
profile = "black"
multi_line_output = 3
skip = [".gitignore", ".dockerignore"]
extend_skip = ["migrations"]