# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1379, 825)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1370, 811))
        self.frame.setStyleSheet("background-color: rgb(84,111,236);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_superior.setStyleSheet("QLabel{\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"QFrame{\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:18px;\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(844, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_min = QtWidgets.QPushButton(self.frame_superior)
        self.btn_min.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_min.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon)
        self.btn_min.setIconSize(QtCore.QSize(36, 36))
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(230,0,0);\n"
"}")
        self.btn_cerrar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon1)
        self.btn_cerrar.setIconSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_2.addWidget(self.btn_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 10px;")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_menu = QtWidgets.QFrame(self.frame_contenido)
        self.frame_menu.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_menu.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.label_5 = QtWidgets.QLabel(self.frame_menu)
        self.label_5.setGeometry(QtCore.QRect(100, 432, 84, 28))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox_camara = QtWidgets.QComboBox(self.frame_menu)
        self.comboBox_camara.setGeometry(QtCore.QRect(67, 467, 170, 32))
        self.comboBox_camara.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_camara.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_camara.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"background-color: rgb(230, 240, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color: #111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:rgb(84,111,236);\n"
"selection-background-color: white;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_camara.setObjectName("comboBox_camara")
        self.btn_conectar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_conectar.setGeometry(QtCore.QRect(57, 252, 190, 50))
        self.btn_conectar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_conectar.setMaximumSize(QtCore.QSize(190, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/log-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_conectar.setIcon(icon2)
        self.btn_conectar.setIconSize(QtCore.QSize(30, 30))
        self.btn_conectar.setObjectName("btn_conectar")
        self.btn_desconectar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_desconectar.setGeometry(QtCore.QRect(57, 317, 190, 50))
        self.btn_desconectar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_desconectar.setMaximumSize(QtCore.QSize(190, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_desconectar.setIcon(icon3)
        self.btn_desconectar.setIconSize(QtCore.QSize(30, 30))
        self.btn_desconectar.setObjectName("btn_desconectar")
        self.label_4 = QtWidgets.QLabel(self.frame_menu)
        self.label_4.setGeometry(QtCore.QRect(90, 122, 107, 28))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox_velocidad = QtWidgets.QComboBox(self.frame_menu)
        self.comboBox_velocidad.setGeometry(QtCore.QRect(67, 157, 170, 32))
        self.comboBox_velocidad.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_velocidad.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_velocidad.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"background-color: rgb(230, 240, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color: #111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:rgb(84,111,236);\n"
"selection-background-color: white;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_velocidad.setObjectName("comboBox_velocidad")
        self.label_2 = QtWidgets.QLabel(self.frame_menu)
        self.label_2.setGeometry(QtCore.QRect(70, 13, 142, 28))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox_puerto = QtWidgets.QComboBox(self.frame_menu)
        self.comboBox_puerto.setGeometry(QtCore.QRect(34, 53, 170, 32))
        self.comboBox_puerto.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_puerto.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"background-color: rgb(230, 240, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color:#111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:#2c2c2c;\n"
"selection-background-color:#ff0037;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_puerto.setObjectName("comboBox_puerto")
        self.btn_actualizar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_actualizar.setGeometry(QtCore.QRect(224, 49, 40, 40))
        self.btn_actualizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_actualizar.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_actualizar.setStyleSheet("border-radius:18px;")
        self.btn_actualizar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/rotate-cw (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_actualizar.setIcon(icon4)
        self.btn_actualizar.setIconSize(QtCore.QSize(25, 25))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.horizontalLayout_3.addWidget(self.frame_menu)
        self.frame_paginas = QtWidgets.QFrame(self.frame_contenido)
        self.frame_paginas.setStyleSheet("QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_paginas)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.frame_paginas)
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu_2 = QtWidgets.QFrame(self.frame_2)
        self.frame_menu_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_menu_2.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_2.setObjectName("frame_menu_2")
        self.btn_guardar = QtWidgets.QPushButton(self.frame_menu_2)
        self.btn_guardar.setGeometry(QtCore.QRect(50, 670, 190, 50))
        self.btn_guardar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_guardar.setMaximumSize(QtCore.QSize(190, 50))
        self.btn_guardar.setStyleSheet("border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.btn_guardar.setIconSize(QtCore.QSize(30, 30))
        self.btn_guardar.setObjectName("btn_guardar")
        self.label_16 = QtWidgets.QLabel(self.frame_menu_2)
        self.label_16.setGeometry(QtCore.QRect(20, 430, 138, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.text_cometarios = QtWidgets.QTextEdit(self.frame_menu_2)
        self.text_cometarios.setGeometry(QtCore.QRect(20, 460, 256, 192))
        self.text_cometarios.setStyleSheet("border:3px solid #111111;\n"
"\n"
"background-color: rgb(255,255,255);")
        self.text_cometarios.setObjectName("text_cometarios")
        self.label_15 = QtWidgets.QLabel(self.frame_menu_2)
        self.label_15.setGeometry(QtCore.QRect(21, 1, 50, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.line_cafe = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_cafe.setGeometry(QtCore.QRect(21, 36, 250, 30))
        self.line_cafe.setMinimumSize(QtCore.QSize(250, 30))
        self.line_cafe.setMaximumSize(QtCore.QSize(230, 30))
        self.line_cafe.setStyleSheet("border:3px solid #111111;")
        self.line_cafe.setObjectName("line_cafe")
        self.label_14 = QtWidgets.QLabel(self.frame_menu_2)
        self.label_14.setGeometry(QtCore.QRect(21, 71, 173, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line_tipo = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_tipo.setGeometry(QtCore.QRect(21, 106, 250, 30))
        self.line_tipo.setMinimumSize(QtCore.QSize(250, 30))
        self.line_tipo.setMaximumSize(QtCore.QSize(230, 30))
        self.line_tipo.setStyleSheet("border:3px solid #111111;")
        self.line_tipo.setObjectName("line_tipo")
        self.line_kilos_in = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_kilos_in.setGeometry(QtCore.QRect(21, 176, 250, 30))
        self.line_kilos_in.setMinimumSize(QtCore.QSize(250, 30))
        self.line_kilos_in.setMaximumSize(QtCore.QSize(230, 30))
        self.line_kilos_in.setStyleSheet("border:3px solid #111111;")
        self.line_kilos_in.setObjectName("line_kilos_in")
        self.label_18 = QtWidgets.QLabel(self.frame_menu_2)
        self.label_18.setGeometry(QtCore.QRect(21, 141, 182, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_menu_2)
        self.label_19.setGeometry(QtCore.QRect(21, 211, 163, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.line_kilos_out = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_kilos_out.setGeometry(QtCore.QRect(21, 246, 250, 30))
        self.line_kilos_out.setMinimumSize(QtCore.QSize(250, 30))
        self.line_kilos_out.setMaximumSize(QtCore.QSize(230, 30))
        self.line_kilos_out.setStyleSheet("border:3px solid #111111;")
        self.line_kilos_out.setObjectName("line_kilos_out")
        self.label_21 = QtWidgets.QLabel(self.frame_menu_2)
        self.label_21.setGeometry(QtCore.QRect(21, 281, 48, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.line_lote = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_lote.setGeometry(QtCore.QRect(21, 316, 250, 30))
        self.line_lote.setMinimumSize(QtCore.QSize(250, 30))
        self.line_lote.setMaximumSize(QtCore.QSize(230, 30))
        self.line_lote.setStyleSheet("border:3px solid #111111;")
        self.line_lote.setObjectName("line_lote")
        self.label_27 = QtWidgets.QLabel(self.frame_menu_2)
        self.label_27.setGeometry(QtCore.QRect(21, 351, 102, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.line_hum = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_hum.setGeometry(QtCore.QRect(21, 386, 250, 30))
        self.line_hum.setMinimumSize(QtCore.QSize(250, 30))
        self.line_hum.setMaximumSize(QtCore.QSize(230, 30))
        self.line_hum.setStyleSheet("border:3px solid #111111;")
        self.line_hum.setObjectName("line_hum")
        self.horizontalLayout.addWidget(self.frame_menu_2)
        self.frame_menu_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_menu_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_menu_3.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_3.setObjectName("frame_menu_3")
        self.timer_1 = QtWidgets.QLabel(self.frame_menu_3)
        self.timer_1.setGeometry(QtCore.QRect(370, 50, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.timer_1.setFont(font)
        self.timer_1.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_1.setObjectName("timer_1")
        self.timer_2 = QtWidgets.QLabel(self.frame_menu_3)
        self.timer_2.setGeometry(QtCore.QRect(370, 90, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.timer_2.setFont(font)
        self.timer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_2.setObjectName("timer_2")
        self.timer_3 = QtWidgets.QLabel(self.frame_menu_3)
        self.timer_3.setGeometry(QtCore.QRect(370, 130, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.timer_3.setFont(font)
        self.timer_3.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_3.setObjectName("timer_3")
        self.valor_3 = QtWidgets.QLabel(self.frame_menu_3)
        self.valor_3.setGeometry(QtCore.QRect(180, 600, 41, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.valor_3.setFont(font)
        self.valor_3.setAlignment(QtCore.Qt.AlignCenter)
        self.valor_3.setObjectName("valor_3")
        self.label_17 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_17.setGeometry(QtCore.QRect(70, 50, 216, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.btn_iniciar_1 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_1.setEnabled(True)
        self.btn_iniciar_1.setGeometry(QtCore.QRect(550, 40, 120, 35))
        self.btn_iniciar_1.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_1.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_1.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,150);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_1.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_1.setObjectName("btn_iniciar_1")
        self.btn_iniciar_3 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_3.setGeometry(QtCore.QRect(550, 80, 120, 35))
        self.btn_iniciar_3.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_3.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_3.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_3.setObjectName("btn_iniciar_3")
        self.label_20 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_20.setGeometry(QtCore.QRect(200, 90, 86, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_22.setGeometry(QtCore.QRect(110, 130, 180, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.btn_iniciar_5 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_5.setGeometry(QtCore.QRect(550, 120, 120, 35))
        self.btn_iniciar_5.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_5.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_5.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_5.setObjectName("btn_iniciar_5")
        self.label_26 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_26.setGeometry(QtCore.QRect(20, 600, 102, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_23 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_23.setGeometry(QtCore.QRect(240, 12, 217, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_25.setGeometry(QtCore.QRect(0, 510, 158, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_28.setGeometry(QtCore.QRect(0, 540, 158, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_29.setGeometry(QtCore.QRect(0, 570, 81, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.valor_4 = QtWidgets.QLabel(self.frame_menu_3)
        self.valor_4.setGeometry(QtCore.QRect(180, 570, 41, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.valor_4.setFont(font)
        self.valor_4.setAlignment(QtCore.Qt.AlignCenter)
        self.valor_4.setObjectName("valor_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_menu_3)
        self.frame_7.setEnabled(True)
        self.frame_7.setGeometry(QtCore.QRect(31, 170, 660, 310))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(170)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(660, 310))
        self.frame_7.setMaximumSize(QtCore.QSize(660, 310))
        self.frame_7.setStyleSheet("QFrame{\n"
"background-color: rgb(240, 250, 255);\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.graph_1 = QtWidgets.QVBoxLayout()
        self.graph_1.setObjectName("graph_1")
        self.horizontalLayout_20.addLayout(self.graph_1)
        self.valor_2 = QtWidgets.QLabel(self.frame_menu_3)
        self.valor_2.setGeometry(QtCore.QRect(190, 540, 26, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.valor_2.setFont(font)
        self.valor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.valor_2.setObjectName("valor_2")
        self.n_2 = QtWidgets.QLabel(self.frame_menu_3)
        self.n_2.setGeometry(QtCore.QRect(220, 540, 16, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.n_2.setFont(font)
        self.n_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n_2.setObjectName("n_2")
        self.valor_1 = QtWidgets.QLabel(self.frame_menu_3)
        self.valor_1.setGeometry(QtCore.QRect(190, 510, 26, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.valor_1.setFont(font)
        self.valor_1.setAlignment(QtCore.Qt.AlignCenter)
        self.valor_1.setObjectName("valor_1")
        self.n_1 = QtWidgets.QLabel(self.frame_menu_3)
        self.n_1.setGeometry(QtCore.QRect(220, 510, 16, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.n_1.setFont(font)
        self.n_1.setAlignment(QtCore.Qt.AlignCenter)
        self.n_1.setObjectName("n_1")
        self.timer_5 = QtWidgets.QLabel(self.frame_menu_3)
        self.timer_5.setGeometry(QtCore.QRect(20, 681, 149, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.timer_5.setFont(font)
        self.timer_5.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_5.setObjectName("timer_5")
        self.timer_4 = QtWidgets.QLabel(self.frame_menu_3)
        self.timer_4.setGeometry(QtCore.QRect(180, 681, 92, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.timer_4.setFont(font)
        self.timer_4.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_4.setObjectName("timer_4")
        self.video = QtWidgets.QLabel(self.frame_menu_3)
        self.video.setGeometry(QtCore.QRect(370, 500, 300, 200))
        self.video.setMinimumSize(QtCore.QSize(300, 200))
        self.video.setMaximumSize(QtCore.QSize(300, 200))
        self.video.setText("")
        self.video.setPixmap(QtGui.QPixmap("images/pngkey.com-granos-de-cafe-png-7800925.png"))
        self.video.setScaledContents(True)
        self.video.setObjectName("video")
        self.label_30 = QtWidgets.QLabel(self.frame_menu_3)
        self.label_30.setGeometry(QtCore.QRect(20, 630, 102, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.frame_color = QtWidgets.QFrame(self.frame_menu_3)
        self.frame_color.setGeometry(QtCore.QRect(190, 630, 21, 21))
        self.frame_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_color.setObjectName("frame_color")
        self.horizontalLayout.addWidget(self.frame_menu_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_36.addLayout(self.horizontalLayout)
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.horizontalLayout_3.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_contenido)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Analisis Tostado de Cafe v1"))
        self.label_5.setText(_translate("MainWindow", "Camara"))
        self.btn_conectar.setText(_translate("MainWindow", "  Conectar"))
        self.btn_desconectar.setText(_translate("MainWindow", "Desconectar"))
        self.label_4.setText(_translate("MainWindow", "Velocidad"))
        self.label_2.setText(_translate("MainWindow", "Puerto Serial"))
        self.btn_guardar.setText(_translate("MainWindow", "Guardar"))
        self.label_16.setText(_translate("MainWindow", "Comentarios"))
        self.text_cometarios.setPlaceholderText(_translate("MainWindow", "Agregue un comentario si lo considera necesario, se guardara junto al set de datos almacenados."))
        self.label_15.setText(_translate("MainWindow", "Cafe"))
        self.line_cafe.setPlaceholderText(_translate("MainWindow", "Nombre del Cafe"))
        self.label_14.setText(_translate("MainWindow", "Tipo de Tostado"))
        self.line_tipo.setPlaceholderText(_translate("MainWindow", "(Medio, Alto, Super)"))
        self.line_kilos_in.setPlaceholderText(_translate("MainWindow", "50"))
        self.label_18.setText(_translate("MainWindow", "Kilos Ingresados"))
        self.label_19.setText(_translate("MainWindow", "Kilos de Salida"))
        self.line_kilos_out.setPlaceholderText(_translate("MainWindow", "40"))
        self.label_21.setText(_translate("MainWindow", "Lote"))
        self.line_lote.setPlaceholderText(_translate("MainWindow", "ABC123"))
        self.label_27.setText(_translate("MainWindow", "Humedad"))
        self.line_hum.setPlaceholderText(_translate("MainWindow", "30"))
        self.timer_1.setText(_translate("MainWindow", "00:00"))
        self.timer_2.setText(_translate("MainWindow", "00:00"))
        self.timer_3.setText(_translate("MainWindow", "00:00"))
        self.valor_3.setText(_translate("MainWindow", "40"))
        self.label_17.setText(_translate("MainWindow", "Calentado de Horno"))
        self.btn_iniciar_1.setText(_translate("MainWindow", "Iniciar"))
        self.btn_iniciar_3.setText(_translate("MainWindow", "Iniciar"))
        self.label_20.setText(_translate("MainWindow", "Tostado"))
        self.label_22.setText(_translate("MainWindow", "Enfriado de Cafe"))
        self.btn_iniciar_5.setText(_translate("MainWindow", "Iniciar"))
        self.label_26.setText(_translate("MainWindow", "Humedad"))
        self.label_23.setText(_translate("MainWindow", "Progreso de Etapas:"))
        self.label_25.setText(_translate("MainWindow", "Temp Grano"))
        self.label_28.setText(_translate("MainWindow", "Temp Horno"))
        self.label_29.setText(_translate("MainWindow", "RoR"))
        self.valor_4.setText(_translate("MainWindow", "40"))
        self.valor_2.setText(_translate("MainWindow", "40"))
        self.n_2.setText(_translate("MainWindow", "°"))
        self.valor_1.setText(_translate("MainWindow", "40"))
        self.n_1.setText(_translate("MainWindow", "°"))
        self.timer_5.setText(_translate("MainWindow", "Tiempo Total:"))
        self.timer_4.setText(_translate("MainWindow", "00:00:00"))
        self.label_30.setText(_translate("MainWindow", "Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
