# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 822)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1370, 811))
        self.frame.setStyleSheet("background-color: rgb(84,111,236);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_superior.setStyleSheet("QLabel{\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"QFrame{\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:18px;\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(844, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_min = QtWidgets.QPushButton(self.frame_superior)
        self.btn_min.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_min.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon)
        self.btn_min.setIconSize(QtCore.QSize(36, 36))
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(230,0,0);\n"
"}")
        self.btn_cerrar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon1)
        self.btn_cerrar.setIconSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_2.addWidget(self.btn_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 10px;")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_menu = QtWidgets.QFrame(self.frame_contenido)
        self.frame_menu.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_menu.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_menu)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_puerto = QtWidgets.QComboBox(self.frame_menu)
        self.comboBox_puerto.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_puerto.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"background-color: rgb(230, 240, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color:#111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:#2c2c2c;\n"
"selection-background-color:#ff0037;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_puerto.setObjectName("comboBox_puerto")
        self.horizontalLayout_4.addWidget(self.comboBox_puerto)
        self.btn_actualizar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_actualizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_actualizar.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_actualizar.setStyleSheet("border-radius:18px;")
        self.btn_actualizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/rotate-cw (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_actualizar.setIcon(icon2)
        self.btn_actualizar.setIconSize(QtCore.QSize(25, 25))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.horizontalLayout_4.addWidget(self.btn_actualizar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_menu)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.comboBox_velocidad = QtWidgets.QComboBox(self.frame_menu)
        self.comboBox_velocidad.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_velocidad.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_velocidad.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"background-color: rgb(230, 240, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color:#111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:#2c2c2c;\n"
"selection-background-color:#ff0037;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_velocidad.setObjectName("comboBox_velocidad")
        self.verticalLayout_2.addWidget(self.comboBox_velocidad)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 82, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_conectar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_conectar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_conectar.setMaximumSize(QtCore.QSize(190, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/log-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_conectar.setIcon(icon3)
        self.btn_conectar.setIconSize(QtCore.QSize(30, 30))
        self.btn_conectar.setObjectName("btn_conectar")
        self.verticalLayout_4.addWidget(self.btn_conectar)
        self.btn_desconectar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_desconectar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_desconectar.setMaximumSize(QtCore.QSize(190, 50))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_desconectar.setIcon(icon4)
        self.btn_desconectar.setIconSize(QtCore.QSize(30, 30))
        self.btn_desconectar.setObjectName("btn_desconectar")
        self.verticalLayout_4.addWidget(self.btn_desconectar)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.label = QtWidgets.QLabel(self.frame_menu)
        self.label.setMinimumSize(QtCore.QSize(150, 150))
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/pngkey.com-granos-de-cafe-png-7800925.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        spacerItem11 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3.addWidget(self.frame_menu)
        self.frame_paginas = QtWidgets.QFrame(self.frame_contenido)
        self.frame_paginas.setStyleSheet("QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_paginas)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.frame_paginas)
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu_2 = QtWidgets.QFrame(self.frame_2)
        self.frame_menu_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_menu_2.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_2.setObjectName("frame_menu_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_menu_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.frame_menu_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.line_cafe = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_cafe.setMinimumSize(QtCore.QSize(250, 30))
        self.line_cafe.setMaximumSize(QtCore.QSize(230, 30))
        self.line_cafe.setStyleSheet("border:3px solid #111111;")
        self.line_cafe.setObjectName("line_cafe")
        self.verticalLayout_14.addWidget(self.line_cafe)
        self.verticalLayout_18.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.frame_menu_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.line_tipo = QtWidgets.QLineEdit(self.frame_menu_2)
        self.line_tipo.setMinimumSize(QtCore.QSize(250, 30))
        self.line_tipo.setMaximumSize(QtCore.QSize(230, 30))
        self.line_tipo.setStyleSheet("border:3px solid #111111;")
        self.line_tipo.setObjectName("line_tipo")
        self.verticalLayout_15.addWidget(self.line_tipo)
        self.verticalLayout_18.addLayout(self.verticalLayout_15)
        spacerItem12 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem12)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem13 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem13)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_23.addLayout(self.verticalLayout_16)
        spacerItem14 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem14)
        self.verticalLayout_18.addLayout(self.horizontalLayout_23)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.frame_menu_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.text_cometarios = QtWidgets.QTextEdit(self.frame_menu_2)
        self.text_cometarios.setStyleSheet("border:3px solid #111111;\n"
"\n"
"background-color: rgb(255,255,255);")
        self.text_cometarios.setObjectName("text_cometarios")
        self.verticalLayout_17.addWidget(self.text_cometarios)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        spacerItem15 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem15)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem16 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem16)
        self.btn_guardar = QtWidgets.QPushButton(self.frame_menu_2)
        self.btn_guardar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_guardar.setMaximumSize(QtCore.QSize(190, 50))
        self.btn_guardar.setStyleSheet("border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;")
        self.btn_guardar.setIconSize(QtCore.QSize(30, 30))
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout_22.addWidget(self.btn_guardar)
        spacerItem17 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_22)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.horizontalLayout.addWidget(self.frame_menu_2)
        self.frame_menu_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_menu_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_menu_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_menu_3.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_3.setObjectName("frame_menu_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_menu_3)
        self.verticalLayout_11.setSpacing(30)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.label_23 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(25)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(50)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.label_17 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.prog_1 = QtWidgets.QProgressBar(self.frame_menu_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prog_1.sizePolicy().hasHeightForWidth())
        self.prog_1.setSizePolicy(sizePolicy)
        self.prog_1.setMinimumSize(QtCore.QSize(221, 0))
        self.prog_1.setStyleSheet("border:3px solid #111111;")
        self.prog_1.setProperty("value", 100)
        self.prog_1.setObjectName("prog_1")
        self.horizontalLayout_7.addWidget(self.prog_1)
        self.btn_iniciar_1 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_1.setEnabled(True)
        self.btn_iniciar_1.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_1.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_1.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,150);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_1.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_1.setObjectName("btn_iniciar_1")
        self.horizontalLayout_7.addWidget(self.btn_iniciar_1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(50)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.label_19 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.prog_2 = QtWidgets.QProgressBar(self.frame_menu_3)
        self.prog_2.setMinimumSize(QtCore.QSize(221, 0))
        self.prog_2.setStyleSheet("border:3px solid #111111;")
        self.prog_2.setProperty("value", 46)
        self.prog_2.setObjectName("prog_2")
        self.horizontalLayout_16.addWidget(self.prog_2)
        self.btn_iniciar_2 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_2.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_2.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,150\n"
");\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_2.setObjectName("btn_iniciar_2")
        self.horizontalLayout_16.addWidget(self.btn_iniciar_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(50)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem22)
        self.label_20 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.prog_3 = QtWidgets.QProgressBar(self.frame_menu_3)
        self.prog_3.setMinimumSize(QtCore.QSize(221, 0))
        self.prog_3.setStyleSheet("border:3px solid #111111;")
        self.prog_3.setProperty("value", 0)
        self.prog_3.setObjectName("prog_3")
        self.horizontalLayout_17.addWidget(self.prog_3)
        self.btn_iniciar_3 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_3.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_3.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_3.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_3.setObjectName("btn_iniciar_3")
        self.horizontalLayout_17.addWidget(self.btn_iniciar_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(50)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem23)
        self.label_21 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.prog_4 = QtWidgets.QProgressBar(self.frame_menu_3)
        self.prog_4.setMinimumSize(QtCore.QSize(221, 0))
        self.prog_4.setStyleSheet("border:3px solid #111111;")
        self.prog_4.setProperty("value", 0)
        self.prog_4.setObjectName("prog_4")
        self.horizontalLayout_18.addWidget(self.prog_4)
        self.btn_iniciar_4 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_4.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_4.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_4.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_4.setObjectName("btn_iniciar_4")
        self.horizontalLayout_18.addWidget(self.btn_iniciar_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(50)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem24)
        self.label_22 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.prog_5 = QtWidgets.QProgressBar(self.frame_menu_3)
        self.prog_5.setMinimumSize(QtCore.QSize(221, 0))
        self.prog_5.setStyleSheet("border:3px solid #111111;")
        self.prog_5.setProperty("value", 0)
        self.prog_5.setObjectName("prog_5")
        self.horizontalLayout_19.addWidget(self.prog_5)
        self.btn_iniciar_5 = QtWidgets.QPushButton(self.frame_menu_3)
        self.btn_iniciar_5.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_5.setMaximumSize(QtCore.QSize(120, 35))
        self.btn_iniciar_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-top-right-radius:80px;\n"
"border-bottom-right-radius:80px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.btn_iniciar_5.setIconSize(QtCore.QSize(30, 30))
        self.btn_iniciar_5.setObjectName("btn_iniciar_5")
        self.horizontalLayout_19.addWidget(self.btn_iniciar_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        spacerItem25 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem25)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem26 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem26)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_10.addWidget(self.label_24)
        self.frame_7 = QtWidgets.QFrame(self.frame_menu_3)
        self.frame_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(170)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(170, 170))
        self.frame_7.setMaximumSize(QtCore.QSize(170, 170))
        self.frame_7.setStyleSheet("QFrame{\n"
"background-color: rgb(240, 250, 255);\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.graph_1 = QtWidgets.QVBoxLayout()
        self.graph_1.setObjectName("graph_1")
        self.horizontalLayout_20.addLayout(self.graph_1)
        self.verticalLayout_10.addWidget(self.frame_7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem27 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem27)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_25 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_12.addWidget(self.label_25)
        self.frame_8 = QtWidgets.QFrame(self.frame_menu_3)
        self.frame_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(170)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(170, 170))
        self.frame_8.setMaximumSize(QtCore.QSize(170, 170))
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color: rgb(240, 250, 255);\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.graph_2 = QtWidgets.QVBoxLayout()
        self.graph_2.setObjectName("graph_2")
        self.horizontalLayout_21.addLayout(self.graph_2)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        spacerItem28 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem28)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_26 = QtWidgets.QLabel(self.frame_menu_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_13.addWidget(self.label_26)
        self.frame_9 = QtWidgets.QFrame(self.frame_menu_3)
        self.frame_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(170)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(170, 170))
        self.frame_9.setMaximumSize(QtCore.QSize(170, 170))
        self.frame_9.setStyleSheet("QFrame{\n"
"background-color: rgb(240, 250, 255);\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.graph_3 = QtWidgets.QVBoxLayout()
        self.graph_3.setObjectName("graph_3")
        self.horizontalLayout_24.addLayout(self.graph_3)
        self.verticalLayout_13.addWidget(self.frame_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        spacerItem29 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem29)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        spacerItem30 = QtWidgets.QSpacerItem(709, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem30)
        spacerItem31 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem31)
        self.horizontalLayout.addWidget(self.frame_menu_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_36.addLayout(self.horizontalLayout)
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.horizontalLayout_3.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_contenido)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Analisis Tostado de Cafe v1"))
        self.label_2.setText(_translate("MainWindow", "Puerto Serial"))
        self.label_4.setText(_translate("MainWindow", "Velocidad"))
        self.btn_conectar.setText(_translate("MainWindow", "  Conectar"))
        self.btn_desconectar.setText(_translate("MainWindow", "Desconectar"))
        self.label_15.setText(_translate("MainWindow", "Cafe"))
        self.line_cafe.setPlaceholderText(_translate("MainWindow", "Nombre del Cafe"))
        self.label_14.setText(_translate("MainWindow", "Tipo de Tostado"))
        self.line_tipo.setPlaceholderText(_translate("MainWindow", "(Medio, Alto, Super)"))
        self.label_16.setText(_translate("MainWindow", "Comentarios"))
        self.text_cometarios.setPlaceholderText(_translate("MainWindow", "Agregue un comentario si lo considera necesario, se guardara junto al set de datos almacenados."))
        self.btn_guardar.setText(_translate("MainWindow", "Guardar"))
        self.label_23.setText(_translate("MainWindow", "Progreso de Etapas:"))
        self.label_17.setText(_translate("MainWindow", "Calentado de Horno"))
        self.btn_iniciar_1.setText(_translate("MainWindow", "Iniciar"))
        self.label_19.setText(_translate("MainWindow", "Ingreso de Cafe"))
        self.btn_iniciar_2.setText(_translate("MainWindow", "Iniciar"))
        self.label_20.setText(_translate("MainWindow", "Tostado"))
        self.btn_iniciar_3.setText(_translate("MainWindow", "Iniciar"))
        self.label_21.setText(_translate("MainWindow", "Salida de Cafe"))
        self.btn_iniciar_4.setText(_translate("MainWindow", "Iniciar"))
        self.label_22.setText(_translate("MainWindow", "Enfriado de Cafe"))
        self.btn_iniciar_5.setText(_translate("MainWindow", "Iniciar"))
        self.label_24.setText(_translate("MainWindow", "Temperatura 1"))
        self.label_25.setText(_translate("MainWindow", "Temperatura 2"))
        self.label_26.setText(_translate("MainWindow", "Humedad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
