# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1407, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1396, 811))
        self.frame.setStyleSheet("background-color: rgb(84,111,236);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_superior.setStyleSheet("QLabel{\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"QFrame{\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:18px;\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_menu = QtWidgets.QPushButton(self.frame_superior)
        self.btn_menu.setMinimumSize(QtCore.QSize(50, 36))
        self.btn_menu.setMaximumSize(QtCore.QSize(50, 36))
        self.btn_menu.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-radius: 5px\n"
"}")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Modulo_CD/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(36, 36))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_2.addWidget(self.btn_menu)
        self.label_3 = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(844, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_min = QtWidgets.QPushButton(self.frame_superior)
        self.btn_min.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_min.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Modulo_CD/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon1)
        self.btn_min.setIconSize(QtCore.QSize(36, 36))
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_max = QtWidgets.QPushButton(self.frame_superior)
        self.btn_max.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_max.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_max.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Modulo_CD/icons/chevrons-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_max.setIcon(icon2)
        self.btn_max.setIconSize(QtCore.QSize(36, 36))
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_2.addWidget(self.btn_max)
        self.btn_normal = QtWidgets.QPushButton(self.frame_superior)
        self.btn_normal.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_normal.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_normal.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Modulo_CD/icons/chevrons-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_normal.setIcon(icon3)
        self.btn_normal.setIconSize(QtCore.QSize(36, 36))
        self.btn_normal.setObjectName("btn_normal")
        self.horizontalLayout_2.addWidget(self.btn_normal)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(230,0,0);\n"
"}")
        self.btn_cerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Modulo_CD/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon4)
        self.btn_cerrar.setIconSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_2.addWidget(self.btn_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 10px;")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_menu = QtWidgets.QFrame(self.frame_contenido)
        self.frame_menu.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_menu.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_menu)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_puerto = QtWidgets.QComboBox(self.frame_menu)
        self.comboBox_puerto.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_puerto.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"background-color: rgb(230, 240, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color:#111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:#2c2c2c;\n"
"selection-background-color:#ff0037;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_puerto.setObjectName("comboBox_puerto")
        self.horizontalLayout_4.addWidget(self.comboBox_puerto)
        self.btn_actualizar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_actualizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_actualizar.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_actualizar.setStyleSheet("border-radius:18px;")
        self.btn_actualizar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/rotate-cw (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_actualizar.setIcon(icon5)
        self.btn_actualizar.setIconSize(QtCore.QSize(25, 25))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.horizontalLayout_4.addWidget(self.btn_actualizar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_menu)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.comboBox_velocidad = QtWidgets.QComboBox(self.frame_menu)
        self.comboBox_velocidad.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_velocidad.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_velocidad.setStyleSheet("QComboBox{\n"
"border:3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width: 6em;\n"
"background-color: rgb(230, 240, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color:#111111;\n"
"border-left-style:solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"background:#2c2c2c;\n"
"selection-background-color:#ff0037;\n"
"color:rgb(218,0,55);\n"
"}")
        self.comboBox_velocidad.setObjectName("comboBox_velocidad")
        self.verticalLayout_2.addWidget(self.comboBox_velocidad)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 82, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_conectar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_conectar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_conectar.setMaximumSize(QtCore.QSize(190, 50))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/log-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_conectar.setIcon(icon6)
        self.btn_conectar.setIconSize(QtCore.QSize(30, 30))
        self.btn_conectar.setObjectName("btn_conectar")
        self.verticalLayout_4.addWidget(self.btn_conectar)
        self.btn_desconectar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_desconectar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_desconectar.setMaximumSize(QtCore.QSize(190, 50))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_desconectar.setIcon(icon7)
        self.btn_desconectar.setIconSize(QtCore.QSize(30, 30))
        self.btn_desconectar.setObjectName("btn_desconectar")
        self.verticalLayout_4.addWidget(self.btn_desconectar)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.label = QtWidgets.QLabel(self.frame_menu)
        self.label.setMinimumSize(QtCore.QSize(150, 150))
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/pngwing.com.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        spacerItem11 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3.addWidget(self.frame_menu)
        self.frame_paginas = QtWidgets.QFrame(self.frame_contenido)
        self.frame_paginas.setStyleSheet("QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_paginas)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.frame_paginas)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 14pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_boca_cerrada = QtWidgets.QPushButton(self.frame_7)
        self.btn_boca_cerrada.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_boca_cerrada.setMaximumSize(QtCore.QSize(190, 50))
        self.btn_boca_cerrada.setIconSize(QtCore.QSize(30, 30))
        self.btn_boca_cerrada.setObjectName("btn_boca_cerrada")
        self.verticalLayout_12.addWidget(self.btn_boca_cerrada)
        self.btn_45_grd = QtWidgets.QPushButton(self.frame_7)
        self.btn_45_grd.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_45_grd.setMaximumSize(QtCore.QSize(190, 50))
        self.btn_45_grd.setIconSize(QtCore.QSize(30, 30))
        self.btn_45_grd.setObjectName("btn_45_grd")
        self.verticalLayout_12.addWidget(self.btn_45_grd)
        self.btn_55_grd = QtWidgets.QPushButton(self.frame_7)
        self.btn_55_grd.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_55_grd.setMaximumSize(QtCore.QSize(190, 50))
        self.btn_55_grd.setIconSize(QtCore.QSize(30, 30))
        self.btn_55_grd.setObjectName("btn_55_grd")
        self.verticalLayout_12.addWidget(self.btn_55_grd)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setEnabled(True)
        self.frame_8.setMinimumSize(QtCore.QSize(200, 200))
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color: rgb(240, 250, 255);\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.img_boca = QtWidgets.QLabel(self.frame_8)
        self.img_boca.setText("")
        self.img_boca.setPixmap(QtGui.QPixmap("images/bocs_cerrada.png"))
        self.img_boca.setScaledContents(True)
        self.img_boca.setObjectName("img_boca")
        self.horizontalLayout_16.addWidget(self.img_boca)
        self.verticalLayout_14.addWidget(self.frame_8)
        self.verticalLayout_29.addLayout(self.verticalLayout_14)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_15.setSpacing(12)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_15.addWidget(self.label_6)
        self.pre = QtWidgets.QLabel(self.frame_4)
        self.pre.setMinimumSize(QtCore.QSize(80, 100))
        self.pre.setMaximumSize(QtCore.QSize(80, 100))
        self.pre.setText("")
        self.pre.setPixmap(QtGui.QPixmap("images/dientes_premolar.png"))
        self.pre.setScaledContents(True)
        self.pre.setObjectName("pre")
        self.horizontalLayout_15.addWidget(self.pre)
        self.verticalLayout_18.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pre_sensor_1 = QtWidgets.QLabel(self.frame_4)
        self.pre_sensor_1.setMinimumSize(QtCore.QSize(80, 100))
        self.pre_sensor_1.setMaximumSize(QtCore.QSize(80, 100))
        self.pre_sensor_1.setText("")
        self.pre_sensor_1.setPixmap(QtGui.QPixmap("images/premolar_blanco.png"))
        self.pre_sensor_1.setScaledContents(True)
        self.pre_sensor_1.setObjectName("pre_sensor_1")
        self.verticalLayout_15.addWidget(self.pre_sensor_1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        self.horizontalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pre_sensor_2 = QtWidgets.QLabel(self.frame_4)
        self.pre_sensor_2.setMinimumSize(QtCore.QSize(80, 100))
        self.pre_sensor_2.setMaximumSize(QtCore.QSize(80, 100))
        self.pre_sensor_2.setText("")
        self.pre_sensor_2.setPixmap(QtGui.QPixmap("images/premolar_blanco.png"))
        self.pre_sensor_2.setScaledContents(True)
        self.pre_sensor_2.setObjectName("pre_sensor_2")
        self.verticalLayout_16.addWidget(self.pre_sensor_2)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8)
        self.horizontalLayout_14.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.pre_sensor_3 = QtWidgets.QLabel(self.frame_4)
        self.pre_sensor_3.setMinimumSize(QtCore.QSize(80, 100))
        self.pre_sensor_3.setMaximumSize(QtCore.QSize(80, 100))
        self.pre_sensor_3.setText("")
        self.pre_sensor_3.setPixmap(QtGui.QPixmap("images/premolar_blanco.png"))
        self.pre_sensor_3.setScaledContents(True)
        self.pre_sensor_3.setObjectName("pre_sensor_3")
        self.verticalLayout_17.addWidget(self.pre_sensor_3)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_17.addWidget(self.label_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_14)
        self.verticalLayout_8.addLayout(self.verticalLayout_18)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_19.setSpacing(12)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_19.addWidget(self.label_10)
        self.pre_2 = QtWidgets.QLabel(self.frame_5)
        self.pre_2.setMinimumSize(QtCore.QSize(80, 100))
        self.pre_2.setMaximumSize(QtCore.QSize(80, 100))
        self.pre_2.setText("")
        self.pre_2.setPixmap(QtGui.QPixmap("images/dientes_molar.png"))
        self.pre_2.setScaledContents(True)
        self.pre_2.setObjectName("pre_2")
        self.horizontalLayout_19.addWidget(self.pre_2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.mo_sensor_1 = QtWidgets.QLabel(self.frame_5)
        self.mo_sensor_1.setMinimumSize(QtCore.QSize(80, 100))
        self.mo_sensor_1.setMaximumSize(QtCore.QSize(80, 100))
        self.mo_sensor_1.setText("")
        self.mo_sensor_1.setPixmap(QtGui.QPixmap("images/molar_blanco.png"))
        self.mo_sensor_1.setScaledContents(True)
        self.mo_sensor_1.setObjectName("mo_sensor_1")
        self.verticalLayout_20.addWidget(self.mo_sensor_1)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_20.addWidget(self.label_11)
        self.horizontalLayout_20.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.mo_sensor_2 = QtWidgets.QLabel(self.frame_5)
        self.mo_sensor_2.setMinimumSize(QtCore.QSize(80, 100))
        self.mo_sensor_2.setMaximumSize(QtCore.QSize(80, 100))
        self.mo_sensor_2.setText("")
        self.mo_sensor_2.setPixmap(QtGui.QPixmap("images/molar_blanco.png"))
        self.mo_sensor_2.setScaledContents(True)
        self.mo_sensor_2.setObjectName("mo_sensor_2")
        self.verticalLayout_21.addWidget(self.mo_sensor_2)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_21.addWidget(self.label_12)
        self.horizontalLayout_20.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.mo_sensor_3 = QtWidgets.QLabel(self.frame_5)
        self.mo_sensor_3.setMinimumSize(QtCore.QSize(80, 100))
        self.mo_sensor_3.setMaximumSize(QtCore.QSize(80, 100))
        self.mo_sensor_3.setText("")
        self.mo_sensor_3.setPixmap(QtGui.QPixmap("images/molar_blanco.png"))
        self.mo_sensor_3.setScaledContents(True)
        self.mo_sensor_3.setObjectName("mo_sensor_3")
        self.verticalLayout_22.addWidget(self.mo_sensor_3)
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_22.addWidget(self.label_13)
        self.horizontalLayout_20.addLayout(self.verticalLayout_22)
        self.verticalLayout_19.addLayout(self.horizontalLayout_20)
        self.verticalLayout_9.addLayout(self.verticalLayout_19)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 12pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(20)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_23.addWidget(self.label_14)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.line_nombre = QtWidgets.QLineEdit(self.frame_6)
        self.line_nombre.setMinimumSize(QtCore.QSize(150, 30))
        self.line_nombre.setMaximumSize(QtCore.QSize(230, 30))
        self.line_nombre.setObjectName("line_nombre")
        self.horizontalLayout_21.addWidget(self.line_nombre)
        self.verticalLayout_23.addLayout(self.horizontalLayout_21)
        self.verticalLayout_25.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_24.addWidget(self.label_15)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.line_matricula = QtWidgets.QLineEdit(self.frame_6)
        self.line_matricula.setMinimumSize(QtCore.QSize(150, 30))
        self.line_matricula.setMaximumSize(QtCore.QSize(230, 30))
        self.line_matricula.setObjectName("line_matricula")
        self.horizontalLayout_22.addWidget(self.line_matricula)
        self.verticalLayout_24.addLayout(self.horizontalLayout_22)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.verticalLayout_10.addLayout(self.verticalLayout_25)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.btn_guardar = QtWidgets.QPushButton(self.frame_6)
        self.btn_guardar.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_guardar.setMaximumSize(QtCore.QSize(190, 50))
        self.btn_guardar.setIcon(icon6)
        self.btn_guardar.setIconSize(QtCore.QSize(30, 30))
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout_11.addWidget(self.btn_guardar)
        spacerItem16 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_26.addWidget(self.label_16)
        self.table_datos = QtWidgets.QTableWidget(self.frame_6)
        self.table_datos.setMinimumSize(QtCore.QSize(387, 400))
        self.table_datos.setMaximumSize(QtCore.QSize(387, 400))
        self.table_datos.setObjectName("table_datos")
        self.table_datos.setColumnCount(10)
        self.table_datos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_datos.setHorizontalHeaderItem(9, item)
        self.verticalLayout_26.addWidget(self.table_datos)
        self.verticalLayout_10.addLayout(self.verticalLayout_26)
        self.horizontalLayout.addWidget(self.frame_6)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.horizontalLayout_3.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_contenido)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Deteccion Premolares/Molares"))
        self.label_2.setText(_translate("MainWindow", "Puerto Serial"))
        self.label_4.setText(_translate("MainWindow", "Velocidad"))
        self.btn_conectar.setText(_translate("MainWindow", "  Conectar"))
        self.btn_desconectar.setText(_translate("MainWindow", "Desconectar"))
        self.label_5.setText(_translate("MainWindow", "Apertura"))
        self.btn_boca_cerrada.setText(_translate("MainWindow", "Boca Cerrada"))
        self.btn_45_grd.setText(_translate("MainWindow", "Boca a 45°"))
        self.btn_55_grd.setText(_translate("MainWindow", "Boca a 55°"))
        self.label_6.setText(_translate("MainWindow", "Dientes Premolares"))
        self.label_7.setText(_translate("MainWindow", "Sensor 1"))
        self.label_8.setText(_translate("MainWindow", "Sensor 2"))
        self.label_9.setText(_translate("MainWindow", "Sensor 3"))
        self.label_10.setText(_translate("MainWindow", "Dientes Molares"))
        self.label_11.setText(_translate("MainWindow", "Sensor 1"))
        self.label_12.setText(_translate("MainWindow", "Sensor 2"))
        self.label_13.setText(_translate("MainWindow", "Sensor 3"))
        self.label_14.setText(_translate("MainWindow", "Nombre"))
        self.label_15.setText(_translate("MainWindow", "Matricula"))
        self.btn_guardar.setText(_translate("MainWindow", "Guadar"))
        self.label_16.setText(_translate("MainWindow", "Base de Datos"))
        item = self.table_datos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.table_datos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Matricula"))
        item = self.table_datos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Premolar 1"))
        item = self.table_datos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Premolar 2"))
        item = self.table_datos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Premolar 3"))
        item = self.table_datos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Molar 1"))
        item = self.table_datos.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Molar 2"))
        item = self.table_datos.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Molar 3"))
        item = self.table_datos.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.table_datos.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Hora"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
